### ISSUE TITLE
Connect all rbpi ground pins to ground plane?

### ISSUE THREAD

**Issue by jackonelli** [BryggansBryggeri/electrical#35]

**Comment by k-forss** [comment]
It depends on a lot of factors. On one hand the stronger ground is connected to itsself the better. But one need to prevent ground loops. [Read this](https://www.autodesk.com/products/eagle/blog/8-pcb-grounding-rules/)

**Comment by jackonelli** [comment]
Since the pi itself connects all ground pins to the ground plane, we'll do the same.
