### ISSUE TITLE
Add Enclosure temperature sensor

### ISSUE THREAD

**Issue by JonathanFager** [BryggansBryggeri/electrical#42]
A temperature sensor within the enclosure might be a good idea, if only as a temporary thing to monitor cabinet temeperatures and might even in thhe future sound buzzer or trigger E-stop if temperature exceeds say 70oC

**Comment by jackonelli** [comment]
Great idea. I think part of it should be implemented. Triggering E-stop seems infeasible though.
How would we control the power to the contactor coil?

**Comment by jackonelli** [comment]
We could of course block all output. But not the input?

**Comment by JonathanFager** [comment]
I know for a fact that we have a DH22 Sensor lying around. Could be mounted directly on the PCB.
Ping @jackonelli to possibly implement this directly.

**Comment by JonathanFager** [comment]
We now got a Ds18b20 in the enclosure.
This works well for all intent and purposes.
Will make a din-clip for ds18b20

**Comment by JonathanFager** [comment]
First design iteration, hopefully it'll fit.
![Ds18b20 clip v2](https://user-images.githubusercontent.com/14237210/70442865-667be180-1a97-11ea-9da9-9fa443d03dbe.png)

**Comment by JonathanFager** [comment]
[ds18b20clip.zip](https://github.com/BryggansBryggeri/electrical/files/3940114/ds18b20clip.zip)

@jackonelli if you can, please start .gcode file extension on the printer.

**Comment by JonathanFager** [comment]
Clip is printed. Probably in the box by the printer at ETA.
