### ISSUE TITLE
Add temp sensors

### ISSUE THREAD

**Issue by jackonelli** [BryggansBryggeri/electrical#46]
- [x] Confirm motherboard v1.0 one-wire interface
- [x] EEschema
- [x] Decide on connectors
- [x] Drill holes for connectors
- [x] Test with connectors

**Comment by jackonelli** [comment]
Do we need to "ground" the signal from connector, directly on motherboard for good signal properties?
The alternative is to wire it directly to NDC DIN-split.

==> One less screw terminal on motherboard.

**Comment by k-forss** [comment]
I would say that it is better to take it to the PCB, otherwise it would be a large zero-resistance loop and would form a quite good transformer

**Comment by JonathanFager** [comment]
2 more distances to be made.
