### ISSUE TITLE
Check resistor values

### ISSUE THREAD

**Issue by jackonelli** [BryggansBryggeri/electrical#49]
Standardise to this:

https://www.electronics-notes.com/articles/electronic_components/resistors/standard-resistor-values-e-series-e3-e6-e12-e24-e48-e96.php

Also: try to minimise the number of unique R values

**Comment by k-forss** [comment]
Reminder: Some resistors need to be as close to a specific value as possible

**Comment by jackonelli** [comment]
Some calcs left. Will open sub issues. Also did capacitors
