### ISSUE TITLE
Pump cabinet design

### ISSUE THREAD

**Issue by jackonelli** [BryggansBryggeri/electrical#5]
- [x] Decide on dimensions of cabinet
- [x] Decide on cable
- [x] Decide on way to communicate with VFD
- [x] Decide on connectors
- [x] Build

**Comment by JonathanFager** [comment]
- [ ] Decide on dimensions of cabinet
- [ ] Decide on cable
- [ ] Decide on way to communicate with VFD
- [ ] Decide on connectors
- [ ] Build

**Comment by jackonelli** [comment]
I think we'll branch off a separate issue for the motherboard/rpbi parts of the comm's.
Then we can close this issue if we only decide on cable for comm's between enclosure and pump cabinet.
@swebro any thoughts? RJ45 is expensive so we can use on of those nice ones Jonte found?
