### ISSUE TITLE
PE on SSR

### ISSUE THREAD

**Issue by jackonelli** [BryggansBryggeri/electrical#51]
I think they are grounded in the DIN-rail, but there seems to be a dedicated screw for it, see page 6:

http://www.productselection.net/pdf/UK/RGC_2_3A.pdf

**Comment by k-forss** [comment]
You are correct, it is however normal to have a redundant connection in these kind of components. We could be content with how it is now, but it is better to also connect the ground screw

**Comment by JonathanFager** [comment]
Today I crimped two wires for ground. However, they where a PITA to get to.
Measured the resistance from the SSR to different points on the enclosure and it was at max 0.7ohm. => More than good enough
@swebro Please move this back to To Do if you disagree, otherwise close the issue

**Comment by k-forss** [comment]
It should be good enough
