### ISSUE TITLE
rbpi din mount

### ISSUE THREAD

**Issue by jackonelli** [BryggansBryggeri/electrical#53]
- [x] design
- [x] 3d print
- [ ] protective plate / cooling system holder

**Comment by jackonelli** [comment]
design at google drive/bryggan180/electrical/raspberry_mount

**Comment by jackonelli** [comment]
The print is fine. Need som distances/bottom plate though since the base of the mount interferes with electronic components on pi

**Comment by JonathanFager** [comment]
Closing this for now.
If internal temperature is to high during operations, we will open a new issue for this.
