### ISSUE TITLE
Mount cable to panelmounted connectors

### ISSUE THREAD

**Issue by JonathanFager** [BryggansBryggeri/electrical#56]
- [x] Decide on cable
- [x] Buy Cable
- [x] Decide on wires to use
- [x] Write in documentation what wires to use.
- [x] Solder to panel mounts
- [x] Mount to raspberry

**Comment by JonathanFager** [comment]
Three Connectors for DS18B20 done. Will stop there for now.

**Comment by jackonelli** [comment]
How will the internal cables connect to the motherboard?

When fixing #17 I removed a lot of screw terminals for ground connection on the motherboard. Now the PCB is _only_ connected to DC ground at the power supply terminal.
