### ISSUE TITLE
#54 Control Powercord on Boilkettle.

### ISSUE THREAD

**Issue by JonathanFager** [BryggansBryggeri/electrical#59]
Make sure to control powercord on boilkettle.

- [x] Heat during extended time on
- [x] Current draw
- [x] Resistance per loop

**Comment by JonathanFager** [comment]
@jackonelli @swebro What was resistance per loop?

**Comment by jackonelli** [comment]
54 ohm from phase to N

**Comment by JonathanFager** [comment]
No issue. Just be a bit thoughtful about this in the future
